### PR TITLE
get from a Map returns either the value for the key or a default

### PR DESCRIPTION
**Pull request by craigmdavidson**
Get a value from a Map or return the supplied default.

```
assertEquals("1", get(map("A", "1", "B", "2", "C", "3"), "A", "4"));
assertEquals("2", get(map("A", "1", "B", "2", "C", "3"), "B", "4"));    
assertEquals("4", get(map("A", "1", "B", "2", "C", "3"), "D", "4")); 
```

### CODE REVIEW

**Comment by martinpllu** [comment]
Do you reckon this is general-purpose enough to include in the library? It's not a situation that I personally encounter that often, and I would have thought the if-null-default behaviour would be easily enough dealt with in client code. Open to being convinced though...

**Comment by craigmdavidson** [comment]
Hi @martinpllu 
Good question. While it's true that you definitely can deal with it in the client code, doing so adds a lot of duplication:
e.g.
```
int value1 = bigOleLumpOfData.get(key1) != null ? bigOleLumpOfData.get(key1) : defaultValue;
int value2 = bigOleLumpOfData.get(key2) != null ? bigOleLumpOfData.get(key2) : defaultValue;
int value3 = bigOleLumpOfData.get(key3) != null ? bigOleLumpOfData.get(key3) : defaultValue;
```
One also may have a tendency to implement this instead as:
```
int value1 = bigOleLumpOfData.contains(key1) ? bigOleLumpOfData.get(key1) : defaultValue;
int value2 = bigOleLumpOfData.contains(key2) ? bigOleLumpOfData.get(key2) : defaultValue;
int value3 = bigOleLumpOfData.contains(key3) ? bigOleLumpOfData.get(key3) : defaultValue;
```
But that dangerous - the dictionary may contain a key but hold a null value against it, which we would then try to box back to an integer. Too much thinking required for one line of code.

And in both cases, the noise to signal ratio if higher than:

```
int value1 = get(bigOleLumpOfData, key1, defaultValue);
int value2 = get(bigOleLumpOfData, key2, defaultValue);
int value3 = get(bigOleLumpOfData, key3, defaultValue);
```

This is especially valuable when nesting these calls:
```
return list(
  get(bigOleLumpOfData, key1, defaultValue),
  Math.abs(
    get(bigOleLumpOfData, key2, defaultValue)),
  get(bigOleLumpOfData, key3, defaultValue));
```

However, it's standard behaviour in clojure and ruby, and I find I miss it a lot that a lot in Java. (In Java I end up writing a private ```nvl``` method (since the first time I became aware of this approach was in Oracle).)
Ruby: https://apidock.com/ruby/Hash/fetch
Clojure: https://clojuredocs.org/clojure.core/get

... and even - https://www.w3schools.com/sql/sql_isnull.asp

Is that enough to convince? ;-)

**Comment by martinpllu** [comment]
The only thing that bothers me with these examples is that there's lots of repetition of that default value and things might get weird when calls from distinct source locations yield different default values.

The other option would be to specify the default value at map initialisation time, possibly using Map.computeIfAbsent. This would require something like mapWithDefault("Dunno", 1, "One", 2, "Two"), or mapWithDefault("Dunno", map(1, "One", 2, "Two"))

Not sure and don't feel too strongly about it, so happy to leave the decision up to you.

**Comment by craigmdavidson** [comment]
Key questions are:
- Is is useful? - Yes - the function is extracted from client code
- Does it exist precedent in other languages? - Yes in pretty much most languages (inc Clojure, Ruby and Python)

**Pull request merged**
